project_id = "x-factor"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]

[analytics]
enabled = false

[edge_runtime]
policy = "per_worker"

[functions.socialMedia]
verify_jwt = false

[functions.turnEngine]
verify_jwt = false

[functions.fandomActions]
verify_jwt = false

[functions.releaseManager]
verify_jwt = false

[functions.festivalActions]
verify_jwt = false

[functions.soundburstRadio]
verify_jwt = false

[functions.touring]
verify_jwt = false

[functions.turnWorker]
verify_jwt = false
